### ISSUE TITLE
Validation errors 

### ISSUE THREAD

**Issue by ziga-lunarg** [LunarG/CrashDiagnosticLayer#109]
When running vkcube with both CDL and VVL enable, there are some validation errors reported:

> UNASSIGNED-API-Version-Violation(ERROR / SPEC): msgNum: -996803404 - Validation Error: [ UNASSIGNED-API-Version-Violation ] Object 0: handle = 0x29ea0168750, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0xc495fcb4 | vkGetPhysicalDeviceFeatures2():  Attempted to call with an effective API version of 1.0.0 (0x00400000), which is the minimum of version requested in pApplicationInfo (1.0.0 (0x00400000)) and supported by this physical device (1.3.287 (0x0040311f)), but this API was not promoted until version 1.1.0 (0x00401000).
> Objects: 1
> [0] 0x29ea0168750, type: 1, name: NULL

And

> SYNC-HAZARD-WRITE-AFTER-WRITE(ERROR / SPEC): msgNum: 1544472022 - Validation Error: \[ SYNC-HAZARD-WRITE-AFTER-WRITE \] Object 0: handle = 0x9fde6b0000000014, type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0x5c0ec5d6 | vkCmdWriteBufferMarkerAMD(): Hazard WRITE_AFTER_WRITE for dstBuffer VkBuffer 0x9fde6b0000000014\[\]. Access info (usage: SYNC_COPY_TRANSFER_WRITE, prior_usage: SYNC_COPY_TRANSFER_WRITE, write_barriers: 0, command: vkCmdWriteBufferMarkerAMD, seq_no: 1, reset_no: 1, resource: VkBuffer 0x9fde6b0000000014\[\]). Objects: 1 \[0\] 0x9fde6b0000000014, type: 9, name: NULL

**Comment by jeremyg-lunarg** [comment]
I can't reproduce either of these errors. Using the sdk packages on either windows or linux and vkconfig to set up layers.

**Comment by jeremyg-lunarg** [comment]
oh duh. For the sync one I need to be on an AMD machine. I'll take another look at that
