### ISSUE TITLE
CTS test hangs when run with CDL

### ISSUE THREAD

**Issue by ziga-lunarg** [LunarG/CrashDiagnosticLayer#131]
Test `dEQP-VK.synchronization.win32_keyed_mutex.write_fill_buffer_read_copy_buffer.buffer_16384_kmt` runs fine on its own, but when CDL is enabled it hangs:

> 00:00:30.692 CDL ERROR: Device error encountered and log being recorded
>         Output written to: "C:\\Users\\nnn\\cdl\\2024-12-01-101535\\cdl_dump.yaml"
> ----------------------------------------------------------------
> 00:00:30.680 CDL ERROR:
> Device error encountered and log being recorded
>         Output written to: "C:\\Users\\nnn\\cdl\\2024-12-01-101535\\cdl_dump.yaml"
> ----------------------------------------------------------------

> # ----------------------------------------------------------------
> # -                    CRASH DIAGNOSTIC LAYER                    -
> # ----------------------------------------------------------------
> 
> version: 1.3.302
> startTime: 2024-12-01 10:15:35
> timeSinceStart: 00:00:30.812
> Settings:
>   output_path: ""
>   trace_on: false
>   dump_queue_submits: running
>   dump_command_buffers: running
>   dump_commands: running
>   dump_shaders: off
>   watchdog_timeout_ms: 30000
>   track_semaphores: true
>   trace_all_semaphores: false
>   instrument_all_commands: true
>   sync_after_commands: false
> SystemInfo:
>   osName: Windows 10 Pro
>   osVersion: 19045
>   osBitdepth: 64-bit
>   osAdditional: Build [vb_release]
>   cpuName: x64
>   numCpus: 32
>   totalRam: 63 GB
>   totalDiskSpace: 3 TB
>   availDiskSpace: 2 TB
> Instance:
>   handle: 0x000001C7DAE54C30 []
>   applicationInfo:
>     application: deqp
>     applicationVersion: 109249085
>     engine: deqp
>     engineVersion: 109249085
>     apiVersion: 1.3.0 (0x00403000)
>   extensions:
>     - VK_KHR_get_surface_capabilitie
> Devi  - VK handle: 0x00000  - VK_KHR_win3  deviceN
>  : NV VK_EXT_debug_report
> 
>     - VK_EXT_: 1.3.300 (
>     - VK_EXT_swapchain_col: 0x8A4
>     - VK_KHR_surface_protect: 0x000010DE
>   devi - V: 0x00002484
>   extensions:
>     - VK_KHR_external_memory_win32
>     - VK_KHR_win32_keyed_mutex
>   Queues:
>     -  # Queue
>       handle: 0x000001C7F7599300[]
>       queueFamilyIndex: 0
>       index: 0
>       flags:
>         - graphics
>         - compute
>         - transfer
>         - sparse
>       completedSeq: 4
>       submittedSeq: 4
>   CommandBuffers:
>     [] - VK_KHR_calibrated_timestamps
>     - VK_KHR_compute_shader_derivatives
>     - VK_KHR_cooperative_matrix
>     - VK_KHR_deferred_host_operations
>     - VK_KHR_dynamic_rendering_local_read
>     - VK_KHR_external_fence_win32
>     - VK_KHR_external_memory_win32
>     - VK_KHR_external_semaphore_win32
>     - VK_KHR_fragment_shader_barycentric
>     - VK_KHR_fragment_shading_rate
>     - VK_KHR_global_priority
>     - VK_KHR_index_type_uint8
>     - VK_KHR_line_rasterization
>     - VK_KHR_load_store_op_none
>     - VK_KHR_maintenance5
>     - VK_KHR_maintenance6
>     - VK_KHR_maintenance7
>     - VK_KHR_map_memory2
>     - VK_KHR_pipeline_binary
>     - VK_KHR_pipeline_executable_properties
>     - VK_KHR_pipeline_library
>     - VK_KHR_present_id
>     - VK_KHR_present_wait
>     - VK_KHR_push_descriptor
>     - VK_KHR_ray_query
>     - VK_KHR_ray_tracing_maintenance1
>     - VK_KHR_ray_tracing_pipeline
>     - VK_KHR_ray_tracing_position_fetch
>     - VK_KHR_shader_clock
>     - VK_KHR_shader_expect_assume
>     - VK_KHR_shader_float_controls2
>     - VK_KHR_shader_maximal_reconvergence
>     - VK_KHR_shader_quad_control
>     - VK_KHR_shader_relaxed_extended_instruction
>     - VK_KHR_shader_subgroup_rotate
>     - VK_KHR_shader_subgroup_uniform_control_flow
>     - VK_KHR_swapchain
>     - VK_KHR_swapchain_mutable_format
>     - VK_KHR_vertex_attribute_divisor
>     - VK_KHR_video_decode_av1
>     - VK_KHR_video_decode_h264
>     - VK_KHR_video_decode_h265
>     - VK_KHR_video_decode_queue
>     - VK_KHR_video_encode_h264
>     - VK_KHR_video_encode_h265
>     - VK_KHR_video_encode_queue
>     - VK_KHR_video_maintenance1
>     - VK_KHR_video_queue
>     - VK_KHR_win32_keyed_mutex
>     - VK_KHR_workgroup_memory_explicit_layout
>     - VK_EXT_4444_formats
>     - VK_EXT_attachment_feedback_loop_dynamic_state
>     - VK_EXT_attachment_feedback_loop_layout
>     - VK_EXT_blend_operation_advanced
>     - VK_EXT_border_color_swizzle
>     - VK_EXT_calibrated_timestamps
>     - VK_EXT_color_write_enable
>     - VK_EXT_conditional_rendering
>     - VK_EXT_conservative_rasterization
>     - VK_EXT_custom_border_color
>     - VK_EXT_depth_bias_control
>     - VK_EXT_depth_clamp_control
>     - VK_EXT_depth_clamp_zero_one
>     - VK_EXT_depth_clip_control
>     - VK_EXT_depth_clip_enable
>     - VK_EXT_depth_range_unrestricted
>     - VK_EXT_descriptor_buffer
>     - VK_EXT_device_fault
>     - VK_EXT_device_generated_commands
>     - VK_EXT_discard_rectangles
>     - VK_EXT_dynamic_rendering_unused_attachments
>     - VK_EXT_extended_dynamic_state
>     - VK_EXT_extended_dynamic_state2
>     - VK_EXT_extended_dynamic_state3
>     - VK_EXT_external_memory_host
>     - VK_EXT_fragment_shader_interlock
>     - VK_EXT_full_screen_exclusive
>     - VK_EXT_graphics_pipeline_library
>     - VK_EXT_hdr_metadata
>     - VK_EXT_host_image_copy
>     - VK_EXT_image_2d_view_of_3d
>     - VK_EXT_image_sliced_view_of_3d
>     - VK_EXT_image_view_min_lod
>     - VK_EXT_index_type_uint8
>     - VK_EXT_legacy_vertex_attributes
>     - VK_EXT_line_rasterization
>     - VK_EXT_load_store_op_none
>     - VK_EXT_memory_budget
>     - VK_EXT_memory_priority
>     - VK_EXT_mesh_shader
>     - VK_EXT_multi_draw
>     - VK_EXT_mutable_descriptor_type
>     - VK_EXT_nested_command_buffer
>     - VK_EXT_non_seamless_cube_map
>     - VK_EXT_opacity_micromap
>     - VK_EXT_pageable_device_local_memory
>     - VK_EXT_pci_bus_info
>     - VK_EXT_pipeline_library_group_handles
>     - VK_EXT_pipeline_robustness
>     - VK_EXT_post_depth_coverage
>     - VK_EXT_present_mode_fifo_latest_ready
>     - VK_EXT_primitive_topology_list_restart
>     - VK_EXT_primitives_generated_query
>     - VK_EXT_provoking_vertex
>     - VK_EXT_queue_family_foreign
>     - VK_EXT_robustness2
>     - VK_EXT_sample_locations
>     - VK_EXT_shader_atomic_float
>     - VK_EXT_shader_image_atomic_int64
>     - VK_EXT_shader_module_identifier
>     - VK_EXT_shader_object
>     - VK_EXT_shader_replicated_composites
>     - VK_EXT_shader_subgroup_ballot
>     - VK_EXT_shader_subgroup_vote
>     - VK_EXT_swapchain_maintenance1
>     - VK_EXT_texel_buffer_alignment
>     - VK_EXT_transform_feedback
>     - VK_EXT_vertex_attribute_divisor
>     - VK_EXT_vertex_attribute_robustness
>     - VK_EXT_vertex_input_dynamic_state
>     - VK_EXT_ycbcr_2plane_444_formats
>     - VK_EXT_ycbcr_image_arrays
>     - VK_NV_clip_space_w_scaling
>     - VK_NV_cooperative_matrix
>     - VK_NV_cooperative_matrix2
>     - VK_NV_coverage_reduction_mode
>     - VK_NV_device_generated_commands
>     - VK_NV_device_generated_commands_compute
>     - VK_NV_fragment_coverage_to_color
>     - VK_NV_framebuffer_mixed_samples
>     - VK_NV_inherited_viewport_scissor
>     - VK_NV_linear_color_attachment
>     - VK_NV_mesh_shader
>     - VK_NV_raw_access_chains
>     - VK_NV_ray_tracing
>     - VK_NV_ray_tracing_invocation_reorder
>     - VK_NV_ray_tracing_motion_blur
>     - VK_NV_representative_fragment_test
>     - VK_NV_scissor_exclusive
>     - VK_NV_shader_atomic_float16_vector
>     - VK_NV_shader_subgroup_partitioned
>     - VK_NV_shading_rate_image
>     - VK_NV_viewport_swizzle
>     - VK_AMD_buffer_marker
>   Queues:
>     []
>   CommandBuffers:
>     []

**Comment by jeremyg-lunarg** [comment]
The code in Queue::Submit() needs to copy the contents of the original pNext and smartly apply it to the broken down submissions it makes. VkWin32KeyedMutexAcquireReleaseInfoKHR acquire stuff needs to be in the first submission and release needs to be in the last, similar to how semaphores are handled. There are several other pNext structs that should be handled as well.
